<a href="https://colab.research.google.com/github/21PA1A6123/DWM-lab/blob/main/DWM_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
a=np.array([[4,5,6],[7,8,9]])
print(a)

[[4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
b=np.append(x,[4,5,6])
print(b)

[1 2 3 4 5 6]


In [ ]:
print("x before deleting",x)
newarray = np.delete(x,1)
print("x after deleting",newarray)

x before deleting [[23 34 46 27]
 [75 19 78 52]
 [ 0 33 88 59]]
x after deleting [23 46 27 75 19 78 52  0 33 88 59]


In [ ]:
b=np.array([8,7,6,5,4,3,6,8,2,3])
b[b>5]= -1
print(b) [ 0 33 88 59]]


[-1 -1 -1  5  4  3 -1 -1  2  3]


In [ ]:
a=np.array([11,22,33,44])
b=np.arange(4)
print(a)
print('\n')
print(b)
print('\n')
print(a+b)
print(a-b)
print(a*b)

[11 22 33 44]


[0 1 2 3]


[11 23 35 47]
[11 21 31 41]
[  0  22  66 132]


In [ ]:
from numpy import random
x=random.randint(100)
print(x)

52


In [ ]:
from numpy import random 
x=random.randint(100,size=(3,4))
print(x)

[[23 34 46 27]
 [75 19 78 52]
 [ 0 33 88 59]]


In [ ]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
